# GitLab CI configuration for litloginfe
# Node.js + esbuild project

stages:
  - build
  - pages

image: node:20

# Cache node_modules between jobs to speed up installs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

# Default setup for all jobs
before_script:
  - node -v
  - npm ci --prefer-offline --no-audit --no-fund

build:app:
  stage: build
  script:
    - npm run build
  artifacts:
    name: "build-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH

# Optional: Publish to GitLab Pages from the dist directory on main/master
pages:
  stage: pages
  needs: ["build:app"]
  script:
    # GitLab Pages expects a ./public folder as the artifact root
    - rm -rf public
    - mkdir -p public
    - cp -r dist/* public/ || true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "master"